# -*- coding: utf-8 -*-
"""VRSU LAB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r0isuQzt6H9O2QewGU5XPJRwhX4mBnt7
"""

# Public Practicals
# Histogram Equalization

import cv2
import numpy as np
import matplotlib.pyplot as plt

# read image in grayscale
img = cv2.imread('/content/vrsu.jpg',0)

# apply histogram equalization
equ = cv2.equalizeHist(img)

# Display results
plt.figure(figsize=(12, 5))

plt.subplot(1, 3, 1)
plt.title('Original')
plt.imshow(img, cmap='gray')

plt.subplot(1, 3, 2)
plt.title('Histogram Equalized')
plt.imshow(equ, cmap='gray')

plt.subplot(1, 3, 3)
plt.title('Equalized (finalized)')
plt.hist(equ.flatten(), 256)

plt.show()

#Point Processing
#CLAHE
import cv2
import matplotlib.pyplot as plt

#Load grayscale image
img = cv2.imread("/content/vrsu 2.1.jpg",0)

#
clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
clahe_img = clahe.apply(img)

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.title('Original')
plt.imshow(img, cmap='gray')
plt.axis('off')

plt.subplot(1,2,2)
plt.title('CLAHE Enhanced')
plt.imshow(clahe_img, cmap='gray')
plt.axis('off')

plt.show()

# Spatial Domain Filtering - Smoothing

import cv2
import matplotlib.pyplot as plt

# -------------------------------
# Load 3 different images
# -------------------------------
img_avg = cv2.imread("/content/vrsu lab 3.jpg")
img_gauss = cv2.imread("/content/micro-peacock-feather-hd-imagebest-260nw-1127238599.webp")
img_median = cv2.imread("/content/ChatGPT Image Dec 13, 2025, 01_23_41 PM.png")

# Check loading
if img_avg is None or img_gauss is None or img_median is None:
    print("Error: One or more images not found. Check file paths!")
    exit()

# Convert BGR → RGB for correct display
img_avg_rgb = cv2.cvtColor(img_avg, cv2.COLOR_BGR2RGB)
img_gauss_rgb = cv2.cvtColor(img_gauss, cv2.COLOR_BGR2RGB)
img_median_rgb = cv2.cvtColor(img_median, cv2.COLOR_BGR2RGB)

# -------------------------------
# Apply filters
# -------------------------------

# 1. Average Smoothing
avg_blur = cv2.blur(img_avg, (5, 5))
avg_blur_rgb = cv2.cvtColor(avg_blur, cv2.COLOR_BGR2RGB)

# 2. Gaussian Smoothing
gaussian_blur = cv2.GaussianBlur(img_gauss, (5, 5), 0)
gaussian_blur_rgb = cv2.cvtColor(gaussian_blur, cv2.COLOR_BGR2RGB)

# 3. Median Smoothing
median_blur = cv2.medianBlur(img_median, 5)
median_blur_rgb = cv2.cvtColor(median_blur, cv2.COLOR_BGR2RGB)

# -------------------------------
# Display Before and After
# -------------------------------
plt.figure(figsize=(14, 10))

# ---- Average Blur ----
plt.subplot(3, 2, 1)
plt.imshow(img_avg_rgb)
plt.title("Original Image (Average Blur)")
plt.axis('off')

plt.subplot(3, 2, 2)
plt.imshow(avg_blur_rgb)
plt.title("After Average Blur")
plt.axis('off')

# ---- Gaussian Blur ----
plt.subplot(3, 2, 3)
plt.imshow(img_gauss_rgb)
plt.title("Original Image (Gaussian Blur)")
plt.axis('off')

plt.subplot(3, 2, 4)
plt.imshow(gaussian_blur_rgb)
plt.title("After Gaussian Blur")
plt.axis('off')

# ---- Median Blur ----
plt.subplot(3, 2, 5)
plt.imshow(img_median_rgb)
plt.title("Original Image (Median Blur)")
plt.axis('off')

plt.subplot(3, 2, 6)
plt.imshow(median_blur_rgb)
plt.title("After Median Blur")
plt.axis('off')

plt.tight_layout()
plt.show()

import cv2
import matplotlib.pyplot as plt
import numpy as np
# Load image in grayscale
img = cv2.imread("/content/Flowers-background-blur.webp", 0)
# Sharpening kernel (simple 3x3 filter)
kernel = np.array([[0, -1, 0],
 [-1, 5, -1],
  [0, -1, 0]])

# Apply sharpening
sharpened = cv2.filter2D(img, -1, kernel)
# Show original and sharpened images
plt.figure(figsize=(10,5))
plt.subplot(1,2,1)
plt.imshow(img, cmap='gray' )
plt.title("Original Image")
plt.axis('off')
plt.subplot(1,2,2)
plt.imshow(sharpened, cmap='gray' )
plt.title("Sharpened Image")
plt.axis('off')
plt. show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read image in grayscale
img = cv2.imread("/content/vrsu3.jpg", 0)

# Check if image is loaded
if img is None:
    raise ValueError("Image not found")

# Apply binary thresholding
threshold_value, binary_img = cv2.threshold(
    img,
    thresh=100,
    maxval=255,
    type=cv2.THRESH_BINARY
)

# Display original and thresholded images
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.title("Original Grayscale Image")
plt.imshow(img, cmap='gray')
plt.axis("off")

plt.subplot(1, 2, 2)
plt.title("Binary Thresholded Image")
plt.imshow(binary_img, cmap='gray')
plt.axis("off")

plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read image in grayscale
img = cv2.imread("/content/vrsu3.jpg", 0)

# Check if image is loaded
if img is None:
    raise ValueError("Image not found")

# Apply Otsu's Thresholding
threshold_value, binary_img = cv2.threshold(
    img,
    100,                      # threshold value set to 0 for Otsu
    255,
    cv2.THRESH_BINARY + cv2.THRESH_OTSU
)

# Display original and thresholded images
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.title("Original Grayscale Image")
plt.imshow(img, cmap='gray')
plt.axis("off")

plt.subplot(1, 2, 2)
plt.title("Otsu Thresholded Image")
plt.imshow(binary_img, cmap='gray')
plt.axis("off")

plt.show()

print("Otsu's computed threshold value:", threshold_value)